# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# Lines configured by zsh-newuser-install
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt autocd
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/paavo/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall


# >>> antigen >>>
source /usr/share/zsh/share/antigen.zsh
antigen use oh-my-zsh
antigen bundle git
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle esc/conda-zsh-completion
antigen theme romkatv/powerlevel10k
antigen apply
# <<< antigen <<<


# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh


# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/home/paavo/miniconda3/bin/conda' 'shell.zsh' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/home/paavo/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/home/paavo/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/home/paavo/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup

if [ -f "/home/paavo/miniconda3/etc/profile.d/mamba.sh" ]; then
    . "/home/paavo/miniconda3/etc/profile.d/mamba.sh"
fi
# <<< conda initialize <<<

