#
# Executes commands at login pre-zshrc.
#

# Language
if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that Zsh searches for programs.
path=(
  /home/paavo/.local/bin
  /home/paavo/.bin
  /usr/local/{bin,sbin}
  $path
)

# run display manager
tdm
