#
# Defines environment variables.

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ ( "$SHLVL" -eq 1 && ! -o LOGIN ) && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'
export LESS='-F -g -i -M -R -S -w -X -z-4'

if [ -f $HOME/.zshenv_envvars ]; then
    source $HOME/.zshenv_envvars
fi

# vpn
alias vpnup='nmcli con up paavo-openvpn'
alias vpndown='nmcli con down paavo-openvpn'

# bluetooth
alias swag='echo -e "connect 98:9E:63:0E:04:4D" | bluetoothctl' 
alias unswag='echo -e "disconnect 98:9E:63:0E:04:4D" | bluetoothctl' 
alias kilburn='echo -e "connect 04:FE:A1:CF:2C:04" | bluetoothctl'
alias unkilburn='echo -e "disconnect 04:FE:A1:CF:2C:04" | bluetoothctl'

# hp stuff
alias selp="/home/paavo/miniconda3/envs/selp/bin/python -m selp"

# other aliases / functions
alias dgg="ssh -i $HOME/.ssh/id_rsa data.gh.gg"
alias ssa="ssh-add $HOME/.ssh/id_rsa"
alias ca="conda activate"
alias jl="conda activate && jupyter lab --no-browser"
function char { printf "$(printf '\\U%08x' 0x$1)\n" }  # print character at code point e.g. `char f011`
alias mysqldd="mysql --defaults-file=~/.mysql/reportingdb.ini"
alias uuid="python -c 'from uuid import uuid4; print(uuid4())'"
