POWERLEVEL9K_MODE='nerdfont-complete'
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(dir dir_writable vcs anaconda)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=()
POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_STATUS_VERBOSE=false
POWERLEVEL9K_SHORTEN_DIR_LENGTH=1
POWERLEVEL9K_SHORTEN_DELIMITER=""
POWERLEVEL9K_SHORTEN_STRATEGY="truncate_from_right"
POWERLEVEL9K_PYTHON_ICON=""
POWERLEVEL9K_TIME_FORMAT='%D{%H:%M}'
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=""
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=" "

#ZLE_RPROMPT_INDENT=0

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
#
# # ex - archive extractor
# # usage: ex <file>
ex ()
{
  if [ -f $1 ] ; then
    case $1 in
      *.tar.bz2)   tar xjf $1   ;;
      *.tar.gz)    tar xzf $1   ;;
      *.bz2)       bunzip2 $1   ;;
      *.rar)       unrar x $1     ;;
      *.gz)        gunzip $1    ;;
      *.tar)       tar xf $1    ;;
      *.tbz2)      tar xjf $1   ;;
      *.tgz)       tar xzf $1   ;;
      *.zip)       unzip $1     ;;
      *.Z)         uncompress $1;;
      *.7z)        7z x $1      ;;
      *)           echo "'$1' cannot be extracted via ex()" ;;
    esac
  else
    echo "'$1' is not a valid file"
  fi
}

source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

# vpn
alias vpnup='nmcli con up paavo-openvpn'
alias vpndown='nmcli con down paavo-openvpn'

# hp stuff
function hp-add { echo "$(date +"%Y-%m-%d %H:%M:%S"),$1" >> $HOME/hp.csv }
alias hp-look="tail $HOME/hp.csv"

# other aliases / functions
alias dgg="ssh -i $HOME/.ssh/dataserver data.gh.gg"
alias ssa="ssh-add $HOME/.ssh/id_rsa"
alias ca="conda activate"
alias jl="jupyter lab || (conda activate && jupyter lab)"
function char { printf "$(printf '\\U%08x' 0x$1)\n" }  # print character at code point e.g. `char f011`

# random customizations
export PATH="$HOME/.bin:$PATH"
source "$HOME/anaconda3/etc/profile.d/conda.sh"
